# Generated by Django 2.0.4 on 2019-02-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=25)),
                ('Phone_number', models.IntegerField()),
                ('Location', models.CharField(max_length=25)),
                ('Qualification', models.CharField(max_length=25)),
                ('attach', models.FileField(upload_to='')),
            ],
        ),
    ]
