# Generated by Django 2.0.4 on 2019-02-25 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20190225_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='attach',
        ),
    ]
