# Generated by Django 2.0.4 on 2019-02-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_email_attach'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='attach',
            field=models.FileField(default=True, upload_to='media'),
        ),
    ]
