# Generated by Django 2.0.4 on 2019-02-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_email_attach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='attach',
            field=models.ImageField(default=True, upload_to='media'),
        ),
    ]
