# Generated by Django 2.0.4 on 2019-02-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_remove_email_attach'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='attach',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
