# Generated by Django 2.0.4 on 2019-02-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_email_attach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='Phone_number',
            field=models.IntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name='email',
            name='attach',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
    ]
