# Generated by Django 2.0.4 on 2019-02-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20190226_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='Phone_number',
            field=models.IntegerField(unique=True),
        ),
    ]
